### ISSUE TITLE
feature request: vim edit mode

### ISSUE THREAD

**Issue by nilsbecker** [ocaml-community/lambda-term#13]
it would be great to have a vi editing mode to the extent that readline provides it. this would remove the last nitpick i have about utop compared to rlwrap ocaml

**Comment by sjfloat** [comment]
+1

This is the only thing preventing my from using utop.

**Comment by ELLIOTTCABLE** [comment]
Would it be possible to implement this via NeoVim? [Lots of actual editors](https://github.com/neovim/neovim/wiki/Related-projects#gui) are doing that for their “vi modes” nowadays; it *might* be a bit heavyweight for this, but it would also result in *real* vi-mode (not “y'know, you can move the cursor with j/k!”, but literal support for every arcane text-object and mapping imaginable).

The API is pretty easy to get one's head around. You can start playing around with [`nvr`](https://github.com/mhinz/neovim-remote) if you want to get an idea for it; then take a look at `nvim`'s `--embed` option

Advantages, at a first blush:

 - Avoiding having to re-implement vi
 - Making the entrenched vi users *very* happy, due to it being one-to-one, and even possibly using their existing config and mappings by default

Disadvantages:

 - Means no vi-integration that the user can just flip on — they have to have NeoVim installed, or install it
 - Some of the development time gained by not having to re-implement vi, is just going to go straight back to figuring out how to map various input *over* to NeoVim, and how to handle various instructions *from* NeoVim in a non-full-screen-editor-setting …
 - Might have to write an API client from scratch (not that that should be too hard, really), as as of my posting, it's not [listed](https://github.com/neovim/neovim/wiki/Related-projects#api-clients) as already having one …

Just a thought!

**Comment by kandu** [comment]
almost done, see https://github.com/ocaml-community/utop/issues/136#issuecomment-610765619
