### ISSUE TITLE
Issue with asian charset

### ISSUE THREAD

**Issue by trefis** [ocaml-community/lambda-term#2]
Hi!

I have been playing with lambda-term and recently I noticed "a bug" in the presence of asian characters. The problem seems to be that the width of such chars is not the same as the one of ones usual ASCII chars.

I think pictures will explain better than words here, so I made a few screenshots to expose the problem.

That picture : http://imgur.com/dxpzw8I,rNVG1su,sn1zKNB#1 is what I expect the layout to be (N.B. the "title" and "status bar" are supposed to be always visible).
And here is what happens when you add korean chars to the mix http://imgur.com/dxpzw8I,rNVG1su,sn1zKNB#0
As you can see the lines containing these chars overflow, which breaks the layout.

If you need any extra information, don't hesitate to ask!

**Comment by diml** [comment]
The latest version of uucp added something about character width in the terminal (see dbuenzli/uucp#5). We can probably use it here.

**Comment by shmibs** [comment]
it makes sense for this to still be an issue, given that unicode support seems lacking in general for ocaml things at the moment. still, it can be very frustrating...

![wide](https://user-images.githubusercontent.com/2358713/49421990-419bb280-f74f-11e8-910e-116da2fb5972.gif)

the most "standard" way of handling this seems to be binding to [ICU](http://site.icu-project.org/), which in its libraries has functions for calculating widths of strings with full-width and  combining characters. it looks like ICU + ocaml isn't a thing yet though [see here](http://site.icu-project.org/related), so maybe discussion needs to be taken upstream

**Comment by diml** [comment]
I wrote a binding to a large part ICU a long time ago. It was long and very boring, and depending on C libraries is always a burden.

We do have good unicode libraries in OCaml, and uucp should have enough to calculate length of characters. However, when I initially wrote lambda-term I had no idea that some characters where using multiple cells when rendered and so it might not be pleasant to retrofit this concept into lambda-term. I would personally recommend switching to notty, which looks more modern.

**Comment by shmibs** [comment]
oh, that's neat to know!
had heard of uucp, but maybe wrote it off too quickly based on a few comments floating around.

for what to use, you probably know best, mmm. am just glad utop is for now a little easier to use still than the default top-level, when it comes to this

thank you for responding! ^_^

**Comment by kandu** [comment]
Hi all. I looked into this issue and tweaked lambda-term and zed a little. No c-stub or other heavy dependencies introduced. It now handles

- combine several chars in one cell, see https://www.unicode.org/faq/char_combmark.html  e.g. â an "a" combines with a hat(2 chars in 1 cell)
- one char occupies several cells e.g. 你好
- one char for one cell e.g. hello

There are some demos in lambda-term's example folder, so let's illustrate some of them.

before tweak:

move
![move](https://user-images.githubusercontent.com/357626/54477774-e9904400-4845-11e9-805e-5433e5e1c1ac.gif)
editor
![editor](https://user-images.githubusercontent.com/357626/54477779-f44ad900-4845-11e9-9b41-8f6aa7e5a118.gif)

after tweak:

move
![ymove](https://user-images.githubusercontent.com/357626/54477783-fca31400-4845-11e9-9291-1025cf4854c6.gif)
editor
![yeditor](https://user-images.githubusercontent.com/357626/54477792-0298f500-4846-11e9-9065-68172a97f1d6.gif)
buttons
![ybuttons](https://user-images.githubusercontent.com/357626/54477892-5526e100-4847-11e9-9cc0-7feb424a9673.gif)

**Comment by shmibs** [comment]
very neat!

which approach have you used?

**Comment by kandu** [comment]
During user editing, the width of the chars in the string vary, and a glyph may consist of a normal char and several combing marks, i.e multipe UChar.t. To deal with that, two module Zed_chat and Zed_string was introduced
``` ocaml
type Zed_char.t= {
  core: UChar.t;
  combined: UChar.t list;
  width: int; (* width of this char *)
  size: int; (* 1 + List.length combined *)
}
```
the type definition of `Zed_string.t` is similar.

In lambda-term, widgets draw chars in an intermediate matrix, an offscreen array
``` ocaml
type point = {
  mutable char : UChar.t;
  mutable bold : bool;
  mutable underline : bool;
  mutable blink : bool;
  mutable reverse : bool;
  mutable foreground : LTerm_style.color;
  mutable background : LTerm_style.color;
}

type matrix = point array array
```
and
```ocaml
type LTerm_geom.size = {
  rows : int;
  cols : int;
}
```

with above definition, a char of wider width will overflow the LTerm_geom.size
So `type point` is redefined as
```ocaml
type point'=
  | Elem of elem
  | WidthHolder of int
```
`type elem` is the original `type point`.

For example, a glyph is of width 3, then a widget will draw it in the matrix as `[| ...; Elem of the glyph; WidthHolder 1; widthHolder 2 ; other glyph...|]`. So these glyphs can't overflow.
The number suffix of a WidthHolder is for convenient, `current_offset - Widthholder num` is the very info of this wider glyph.

The last step is rendering, which's simple, `match point with | Elem elem-> render elem | WidthHolder _-> ()`

As for width calculating, we should consider not only the unicode standard but also the compatibility of terminal's behaviour. I wrote a project in pure OCaml to deal with it. [charInfo_width](https://bitbucket.org/zandoye/charinfo_width). The default calculating method is the same as xterm/ncursesw and it's extensible on demand if necessary(we can also load extra width table from an OCaml source file because it implements an interpreter in less than 400 loc to support a subset of OCaml language ).

**Comment by kandu** [comment]
What is the best way to integrate the retrofit to zed/lambda-term?

It causes all the related source code to be changed that we now use Zed_char.t and Zed_string.t instead of raw string as the essential type, so does the API.

Currently, the original code was not touched. All new code is named as yed_xxx.ml or yTerm_xxx.ml in zed or lambda-term respectively.

Shall we keep these code coexists and release a minor version(LTerm_xxx, YTerm_xxx apis coexist), or we apply these changes to zed/lambda-term and bump the major version of the two projects, or release the retrofit as separate projects?

**Comment by diml** [comment]
I can see two options:
1. break the API and release a new major version of zed and lambda-term
2. encode `WidthHolder n` as `UChar.t` values. For instance, we could choose a few non-printable characters and use them for this purpose

**Comment by pmetzger** [comment]
My gut reaction is that in-band magic characters seem like trouble waiting to happen.

**Comment by diml** [comment]
Yh, it would be less clean for sure. Though changing the types would cause more work for users of lambda-term.

TBH, one thing that makes me sad here is that we have several independent terminal libraries in OCaml, the same work has to be done for all of them and nothing can be shared. I'd much rather see work done in the direction of sharing more code between them. Even if that means breaking the API, at least we'd end up in a better world.

**Comment by pmetzger** [comment]
So perhaps we need to break the APIs a bit.

**Comment by kandu** [comment]
These tweaks had been merged into my forks. I added a LiteralIntf module to wrap the user level interfaces of lTerm_widget and lTerm_text and chose UTF8 as the default literal encoding so that  almost all demos in the examples folder are compiled without any modification. We break the APIs only a little bit.

Since these tweaks modified not only one project and one of them depends on another, I'm not sure if it's fine to submit PRs directly.

Here are the branches:
* https://github.com/kandu/zed/tree/width  main changes: new modules: Zed_char Zed_string, refactored Zed_rope.t based on new modules. Some small tweak to make zed aware of wider/combined glyphs.
* https://github.com/kandu/lambda-term/tree/width  main changes: depends on the new zed. Some small tweaks in lTerm_draw, lTerm_widget, lTerm_read_line to make it render glyphs properly.

![utop](https://user-images.githubusercontent.com/357626/55277607-3a6f6480-533d-11e9-99da-56fe2da71efc.gif)

**Comment by diml** [comment]
> Since these tweaks modified not only one project and one of them depends on another, I'm not sure if it's fine to submit PRs directly.

It's fine to submit the PRs directly. In fact it's better to submit the various PRs at the same time so that we can see the global picture. Just mention in each PRs what other PRs they depend on.

**Comment by kandu** [comment]
I've been thinking about whether to open a new issue to release and discuss the preview versions of zed, lambda-term and utop. Given that the discussion above gives us context about the issue, we may continue to talk here.

Since it retrofits and refactors a somewhat part of zed and lambda-term which is error-prone and the API is therefore changed a bit, informal preview releases go first.

For technical details and discussion, here are the PRs
* ocaml-community/zed#12
* ocaml-community/lambda-term#71
* ocaml-community/utop#278

And for the informal preview releases,
`opam repository add NameItYourself hg+https://bitbucket.org/zandoye/opam-repo`
then you can opam install zed 2.0-preview.0, lambda-term 2.0-preview.0 and utop 2.4.0-preview.0 for a try.

Any feedback, suggestion, testing, code review, doc/comment polishing are highly welcome.

**Comment by kandu** [comment]
* zed 2.0~preview.1
* lambda-term 2.0~preview.1
* utop 2.4~preview.1
are available.

We can even input, edit and display malformed Zed_char.t or Zed_string.t(a char or string staring with combining marks) now.

The old -preview.0 versions are renamed to ~preview.0. If you're using the -preview.0 versions, please remove them before installing the new releases.

**Comment by pmetzger** [comment]
Is everything merged now?

**Comment by kandu** [comment]
Yes, all three PRs are merged.

**Comment by pmetzger** [comment]
So this should probably be closed and the three packages should get new releases.

**Comment by kandu** [comment]
Yes, release them, and let the upcoming bug reports pop up because I'm skillful at writing bugs.

**Comment by kandu** [comment]
Just joking. If no objection, we can close this issue and make new releases.

**Comment by kandu** [comment]
* zed 2.0~beta.0
* lambda-term 2.0~beta.0
* utop 2.4.0~beta.0
are available

Main changes:
1. In the read_line widget, when a wider glyph hits the right margin and therefore floats down, the wider space will be properly padded and the cursor position will be updated properly too.
2. Lterm_edit: Horizontal scrolling for wider glyph is implemented.

Invoke `opam install utop.2.4.0~beta.0` to have a try :)
