### ISSUE TITLE
The "clock" and "modal" examples do not work

### ISSUE THREAD

**Issue by jonathan-laurent** [ocaml-community/lambda-term#98]
The "clock" and "modal" examples are not working for me:

- Regarding "clock", the current time is shown and updated correctly but the "exit" button does not appear to be working.
- Regarding "modal", neither of the "exit" or "change counter" button are working. 

I tested this behavior both on a MacOS and Ubuntu, using different terminal emulators.
Note that other examples involving buttons and widgets such as "checkbuttons", "radiobuttons" and "double_editor" are working on both systems.

**Configuration:** OCaml 4.11.1, lambda-term 3.1.0 (#master), lwt (5.3.0).

**Comment by avysk** [comment]
Actually, both examples are still working perfectly except that they do not support mouse (using arrow keys and Enter helps). I do not think there was any mouse support at all when these examples were written (I wrote `modal.ml` in 2014 and it was never update since then). I'll update the examples, it looks rather trivial.
